### ISSUE TITLE
附件无法自定义上传路径

### ISSUE THREAD

**Issue by xiamujun** [dhcn/DUEditor#1]
description = UEditorField(verbose_name='描述', height=200, width=700, default='test', toolbars='besttome', imagePath="uploads/images/",filePath='uploads/files/',blank=True)

后端表设计的时候设置了图片、文件上传路径，但是通过插件贴图、上传文件 依旧上传至OSS bucket下的upfiles/1 目录

**Comment by dhcn** [comment]
之前的路径传参可能造成安全隐患，目前这个上传路径的设置全部统一到项目的settings.py里面了。
