### ISSUE TITLE
老大能够出一个简单而完整的案例吗

### ISSUE THREAD

**Issue by my96131013** [dhcn/DUEditor#10]
本人初学Django，下载了这里全站的源代码在win10+Django2.2+Python3.8.1+vscode或PyCharm下始终运行不了，按照使用说明所做尝试也搞不成功，因为这个说明对初学者实在省略了太多的东西了，折腾了两天没搞定，快要崩溃了~~~~如果有时间的话，老大能不能出一个简单而又能用的演示百度剪辑器集成到Django的教程呢？比如说第一步在哪个文件干什么，第二部干什么，每个需要修改代码的文件都贴出来，其他地方不要美化，尽量越简单越好，只要满足编辑器显示出来，编辑一些东西，上传一些图片等功能，然后提交保存到数据库，然后再从数据库取出来显示在前端

**Comment by dhcn** [comment]
默认启动的DUSite就是一个使用样例

**Comment by dhcn** [comment]
启动以后，跑 http://127.0.0.1:8000/test/ 这个地址看到样例

**Comment by dhcn** [comment]
上传的主入口在DUEditor/views.py中的get_ueditor_controller函数，为了安全，这个函数设置了必须登录后才能访问。

**Comment by dhcn** [comment]
这个是一个Django plugin,使用前请认真做好Django的资料功课
