### ISSUE TITLE
options={"elementPathEnabled":True}会TypeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by chengxiao** [dhcn/DUEditor#2]
class Blog(models.Model):
	Name=models.CharField(,max_length=100,blank=True)
	Content=UEditorField('内容	',height=100,width=500,default='test',toolbars='mini',options={"elementPathEnabled":True},blank=True)
TypeError: __init__() got an unexpected keyword argument 'options'

**Comment by dhcn** [comment]
__init__(self,verbose_name=None, width=600, height=300, toolbars="full",imagePath="", filePath="",upload_settings={},settings={},command=None,event_handler=None ,**kwargs):
这个是models的UEditorField的初始化函数签名，
建议在form里面用UEditorField
