### ISSUE TITLE
你好，关于代码过长的显示问题。

### ISSUE THREAD

**Issue by PiercJ** [dhcn/DUEditor#5]
感谢贡献，项目已经嵌入到我的项目里面了，很好用，但是有疑问，代码显示过长的时候，不会自动换行；或者说代码下面没有滚动条。请问，过长，怎样设置滚动条，或者让代码自动换行呢？谢谢

**Comment by dhcn** [comment]
这个问题你可以研究一下Ueditor的完整配置，看能不能配置。

**Comment by PiercJ** [comment]
好的
