### ISSUE TITLE
在xadmin后台使用时，在模型中如有datefield或datetimefield字段将使该字段js无法使用

### ISSUE THREAD

**Issue by z3630275** [dhcn/DUEditor#6]
在xadmin后台使用时，在模型中如有datefield或datetimefield字段将使该字段js无法使用，手动添加还是能正常保存模型

**Comment by dhcn** [comment]
可能是JS的加载冲突，可以的话，你可以把你的输出HTML 贴出来我们看一下。

**Comment by z3630275** [comment]
应该是JS 冲突，只要禁用ueditor或者没有editor的页码xadmin的datefield和datetimefield字段就可以用了
